version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend/multi-agent-frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend