"""
Exercise Recommendation Model
-----------------------------

Stores AI-generated exercise recommendations for a user
based on recorded health metrics.

Instead of duplicating health metrics, this table references
the health_metrics table through a foreign key.

Used by:
- Exercise Agent
- Health Monitoring System
"""

from sqlalchemy import Column, BigInteger, Integer, String, Text, DateTime, ForeignKey
from datetime import datetime

# Shared Base
from app.database import Base

# Logging
from app.core.logging_config import setup_logger

logger = setup_logger(__name__)


class ExerciseRecommendation(Base):
    """
    Database table storing LLM-generated exercise
    recommendations linked to a specific health metric record.
    """

    __tablename__ = "exercise_recommendations"

    # ---------------------------------------------------------
    # Primary Identifier
    # ---------------------------------------------------------

    id = Column(Integer, primary_key=True, index=True)

    # ---------------------------------------------------------
    # Foreign Key References
    # ---------------------------------------------------------

    user_id = Column(
        Integer,
        ForeignKey("users.user_id"),
        nullable=False,
        index=True
    )
    """
    Reference to the user receiving the recommendation.
    """

    health_metric_id = Column(
        Integer,
        ForeignKey("health_metrics.id"),
        nullable=True,
        index=True
    )
    """
    Reference to the health metric snapshot used
    to generate this recommendation.
    """

    # ---------------------------------------------------------
    # LLM Generated Recommendations
    # ---------------------------------------------------------

    llm_response = Column(Text, nullable=True)
    """
    Full raw response returned from the LLM.
    """

    intensity = Column(String(50), nullable=True)
    """
    Recommended workout intensity
    (low / medium / high).
    """

    plan = Column(Text, nullable=True)
    """
    Exercise plan generated by the LLM.
    Stored as JSON stringified list.
    """

    warnings = Column(Text, nullable=True)
    """
    Health warnings generated by the LLM.
    Stored as JSON stringified list.
    """

    recovery_advice = Column(Text, nullable=True)
    """
    Recovery advice provided by the LLM.
    """

    # ---------------------------------------------------------
    # Metadata
    # ---------------------------------------------------------

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True
    )

    # ---------------------------------------------------------
    # Representation
    # ---------------------------------------------------------

    def __repr__(self):
        """
        Developer-friendly string representation.
        Useful for debugging and logging.
        """
        return (
            f"<ExerciseRecommendation("
            f"id={self.id}, "
            f"user_id={self.user_id}, "
            f"health_metric_id={self.health_metric_id}, "
            f"intensity={self.intensity}, "
            f"created_at={self.created_at})>"
        )

    # ---------------------------------------------------------
    # Logging Helper
    # ---------------------------------------------------------

    def log_creation(self):
        """
        Log entry creation for debugging and monitoring.
        """
        logger.info(
            f"Exercise recommendation created | "
            f"user_id={self.user_id} | "
            f"health_metric_id={self.health_metric_id} | "
            f"intensity={self.intensity}"
        )