"""
ExerciseEntry SQLAlchemy Model
------------------------------

Represents exercise recommendations generated for a user based on
health metrics. This table stores both the raw health data and the
LLM-generated exercise plan.

Used by:
- Exercise Agent
- Health Monitoring System
"""

from sqlalchemy import Column, BigInteger, Integer, Float, String, Text, DateTime
from datetime import datetime

# Use shared Base from database module
from app.database import Base

# Logging
from app.core.logging_config import setup_logger

logger = setup_logger(__name__)


class ExerciseEntry(Base):
    """
    Database table storing health metrics and exercise recommendations
    generated by the Exercise Agent.
    """

    __tablename__ = "exercise_entries"

    # ---------------------------------------------------------
    # Primary Identifier
    # ---------------------------------------------------------

    id = Column(BigInteger, primary_key=True, autoincrement=True)

    # ---------------------------------------------------------
    # User Reference
    # ---------------------------------------------------------

    user_id = Column(BigInteger, nullable=False, index=True)

    # ---------------------------------------------------------
    # Health Metrics
    # ---------------------------------------------------------

    heart_rate = Column(Integer, nullable=True)
    """Heart rate in beats per minute"""

    spo2 = Column(Integer, nullable=True)
    """Blood oxygen saturation percentage"""

    bp_systolic = Column(Integer, nullable=True)
    """Systolic blood pressure"""

    bp_diastolic = Column(Integer, nullable=True)
    """Diastolic blood pressure"""

    steps = Column(Integer, nullable=True)
    """Total steps recorded"""

    workout_duration_minutes = Column(Float, nullable=True)
    """Recommended or completed workout duration"""

    # ---------------------------------------------------------
    # LLM Generated Recommendations
    # ---------------------------------------------------------

    llm_response = Column(Text, nullable=True)
    """Full response returned from the LLM"""

    intensity = Column(String(50), nullable=True)
    """Recommended workout intensity (low / medium / high)"""

    plan = Column(Text, nullable=True)
    """
    Exercise plan generated by the LLM.
    Stored as JSON stringified list.
    """

    warnings = Column(Text, nullable=True)
    """
    Health warnings generated by the LLM.
    Stored as JSON stringified list.
    """

    recovery_advice = Column(Text, nullable=True)
    """Recovery advice provided by the LLM"""

    # ---------------------------------------------------------
    # Metadata
    # ---------------------------------------------------------

    date_created = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True
    )

    # ---------------------------------------------------------
    # Representation
    # ---------------------------------------------------------

    def __repr__(self):
        """
        Developer-friendly string representation.
        Useful for debugging and logging.
        """
        return (
            f"<ExerciseEntry("
            f"id={self.id}, "
            f"user_id={self.user_id}, "
            f"intensity={self.intensity}, "
            f"date_created={self.date_created})>"
        )

    # ---------------------------------------------------------
    # Logging Helper
    # ---------------------------------------------------------

    def log_creation(self):
        """
        Log entry creation for debugging and monitoring.
        """
        logger.info(
            f"ExerciseEntry created | user_id={self.user_id} | intensity={self.intensity}"
        )
# """
# SQLAlchemy model for Exercise Agent entries.
# """

# from sqlalchemy import Column, BigInteger, Integer, Float, String, Text, DateTime
# from sqlalchemy.orm import declarative_base
# from datetime import datetime

# Base = declarative_base()


# class ExerciseEntry(Base):
#     """
#     Stores user health metrics and LLM-based exercise recommendations.
#     """

#     __tablename__ = "exercise_entries"

#     id = Column(BigInteger, primary_key=True, autoincrement=True)
#     user_id = Column(BigInteger, nullable=False)
#     heart_rate = Column(Integer, nullable=True)
#     spo2 = Column(Integer, nullable=True)
#     bp_systolic = Column(Integer, nullable=True)
#     bp_diastolic = Column(Integer, nullable=True)
#     steps = Column(Integer, nullable=True)
#     workout_duration_minutes = Column(Float, nullable=True)
#     llm_response = Column(Text, nullable=True)
#     intensity = Column(String(50), nullable=True)
#     plan = Column(Text, nullable=True)  # JSON stringified list
#     warnings = Column(Text, nullable=True)  # JSON stringified list
#     recovery_advice = Column(Text, nullable=True)
#     date_created = Column(DateTime, default=datetime.utcnow)

#     def __repr__(self):
#         return (
#             f"<ExerciseEntry(id={self.id}, user_id={self.user_id}, "
#             f"intensity={self.intensity}, date_created={self.date_created})>"
#         )