"""
Weekly Meal Plan Model
----------------------

Stores AI-generated weekly nutrition plans for a user.
The plan is generated by the Nutrition Agent and later
approved by the user before grocery recommendations
are produced.

This table contains:
• User preferences used for generation
• Generated meal plan text
• Grocery list extracted from the plan
• Approval status
"""

from sqlalchemy import Column, Integer, String, Text, Boolean, JSON, DateTime
from sqlalchemy.sql import func

from app.database import Base
from app.core.logging_config import setup_logger

# Initialize logger
logger = setup_logger(__name__)


class WeeklyMealPlan(Base):
    """
    SQLAlchemy model representing a weekly meal plan
    generated by the Nutrition Agent.
    """

    __tablename__ = "weekly_meal_plans"

    # ---------------------------------------------------------
    # Primary Identifier
    # ---------------------------------------------------------

    id = Column(Integer, primary_key=True, index=True)

    # ---------------------------------------------------------
    # User Reference
    # ---------------------------------------------------------

    user_id = Column(Integer, index=True, nullable=False)
    """
    ID of the user for whom the meal plan was generated.
    Indexed to allow fast retrieval of plans per user.
    """

    # ---------------------------------------------------------
    # User Preferences Used For Plan Generation
    # ---------------------------------------------------------

    calories = Column(Integer, nullable=True)
    """Target daily calorie intake"""

    diet = Column(String(50), nullable=True)
    """Diet type (vegetarian, vegan, keto, etc.)"""

    region = Column(String(50), nullable=True)
    """Region-based cuisine preference"""

    goal = Column(String(50), nullable=True)
    """Health goal (weight loss, maintenance, muscle gain)"""

    restrictions = Column(JSON, nullable=True)
    """
    Dietary restrictions such as:
    ["no dairy", "gluten free"]
    Stored as JSON list.
    """

    # ---------------------------------------------------------
    # Generated Outputs From Nutrition Agent
    # ---------------------------------------------------------

    meal_plan_text = Column(Text, nullable=False)
    """
    Full weekly meal plan generated by the LLM.
    Stored as plain text.
    """

    grocery_list = Column(JSON, nullable=True)
    """
    Grocery items extracted from the meal plan.
    Stored as JSON list for easier processing.
    """

    # ---------------------------------------------------------
    # Approval Status
    # ---------------------------------------------------------

    is_approved = Column(Boolean, default=False)
    """
    Indicates whether the user approved the generated meal plan.
    Grocery recommendations are only generated after approval.
    """

    # ---------------------------------------------------------
    # Metadata
    # ---------------------------------------------------------

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        index=True
    )
    """
    Timestamp when the meal plan was generated.
    Indexed for faster chronological queries.
    """

    # ---------------------------------------------------------
    # Representation
    # ---------------------------------------------------------

    def __repr__(self):
        """
        Developer-friendly representation for debugging.
        """
        return (
            f"<WeeklyMealPlan("
            f"id={self.id}, "
            f"user_id={self.user_id}, "
            f"diet={self.diet}, "
            f"goal={self.goal}, "
            f"is_approved={self.is_approved}, "
            f"created_at={self.created_at})>"
        )

    # ---------------------------------------------------------
    # Logging Helper
    # ---------------------------------------------------------

    def log_creation(self):
        """
        Log creation of a meal plan.
        """
        logger.info(
            f"Meal plan created | user_id={self.user_id} | "
            f"diet={self.diet} | goal={self.goal}"
        )
# from sqlalchemy import Column, Integer, String, Text, Boolean, JSON, DateTime
# from sqlalchemy.sql import func
# from app.database import Base


# class WeeklyMealPlan(Base):
#     __tablename__ = "weekly_meal_plans"

#     id = Column(Integer, primary_key=True, index=True)

#     user_id = Column(Integer, index=True)

#     # user preferences used to generate meal plan
#     calories = Column(Integer, nullable=True)
#     diet = Column(String(50), nullable=True)
#     region = Column(String(50), nullable=True)
#     goal = Column(String(50), nullable=True)
#     restrictions = Column(JSON, nullable=True)

#     # generated outputs
#     meal_plan_text = Column(Text, nullable=False)
#     grocery_list = Column(JSON, nullable=True)

#     is_approved = Column(Boolean, default=False)

#     # timestamp when plan is generated
#     created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)