"""
Weekly Meal Plan Model
----------------------

Stores AI-generated weekly nutrition plans for a user.

The plan is generated by the Nutrition Agent and later
approved by the user before grocery recommendations
are produced.
"""

from sqlalchemy import Column, Integer, String, Text, Boolean, JSON, DateTime, ForeignKey
from sqlalchemy.sql import func

from app.database import Base
from app.core.logging_config import setup_logger

# Initialize logger
logger = setup_logger(__name__)


class WeeklyMealPlan(Base):
    """
    SQLAlchemy model representing a weekly meal plan
    generated by the Nutrition Agent.
    """

    __tablename__ = "weekly_meal_plans"

    # ---------------------------------------------------------
    # Primary Identifier
    # ---------------------------------------------------------
    id = Column(Integer, primary_key=True, index=True)

    # ---------------------------------------------------------
    # User Reference
    # ---------------------------------------------------------
    user_id = Column(
        Integer,
        ForeignKey("users.user_id"),
        nullable=False,
        index=True
    )
    """User for whom the meal plan is generated"""

    # ---------------------------------------------------------
    # User Preferences Used For Plan Generation
    # ---------------------------------------------------------
    calories = Column(Integer, nullable=True)
    """Target daily calorie intake"""

    diet = Column(String(50), nullable=True)
    """Diet type (vegetarian, vegan, keto, etc.)"""

    region = Column(String(50), nullable=True)
    """Cuisine preference based on region"""

    goal = Column(String(50), nullable=True)
    """Health goal: weight_loss, maintenance, muscle_gain"""

    restrictions = Column(JSON, nullable=True)
    """
    Dietary restrictions such as:
    ["no dairy", "gluten free"]
    """

    # ---------------------------------------------------------
    # Generated Outputs From Nutrition Agent
    # ---------------------------------------------------------
    meal_plan_text = Column(Text, nullable=False)
    """Full weekly meal plan generated by the LLM"""

    grocery_list = Column(JSON, nullable=True)
    """Grocery list extracted from the meal plan"""

    shop_number = Column(String(20), nullable=True)
    """Grocery store number for shopping"""

    # ---------------------------------------------------------
    # Approval Status
    # ---------------------------------------------------------
    is_approved = Column(Boolean, default=False)
    """Indicates if the user approved the generated meal plan"""

    # ---------------------------------------------------------
    # Metadata
    # ---------------------------------------------------------
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        index=True
    )
    """Timestamp when the meal plan was created"""

    # ---------------------------------------------------------
    # Representation (for debugging)
    # ---------------------------------------------------------
    def __repr__(self):
        return (
            f"<WeeklyMealPlan("
            f"id={self.id}, "
            f"user_id={self.user_id}, "
            f"diet={self.diet}, "
            f"goal={self.goal}, "
            f"is_approved={self.is_approved}, "
            f"created_at={self.created_at})>"
        )

    # ---------------------------------------------------------
    # Logging Helper
    # ---------------------------------------------------------
    def log_creation(self):
        """Log when a meal plan is created"""
        logger.info(
            f"Meal plan created | "
            f"user_id={self.user_id} | "
            f"diet={self.diet} | "
            f"goal={self.goal}"
        )