"""
Orchestrator State Definition
-----------------------------

Defines the shared state used by the LangGraph orchestrator.

Each agent reads from and writes to this state during workflow execution.

Design Goals
------------
• Centralized state management
• Loose coupling between agents
• Clear typing for maintainability
"""

from typing import TypedDict, Optional, List, Dict
from sqlalchemy.orm import Session


class OrchestratorState(TypedDict, total=False):
    """
    Shared state passed between agents in the LangGraph workflow.

    All fields are optional (`total=False`) because each agent
    may populate only the data it produces.
    """

    # ---------------------------------------------------------
    # Core User Context
    # ---------------------------------------------------------

    user_id: int
    """Unique identifier for the logged-in user"""

    user_profile: Dict
    """
    User profile containing preferences such as:
    - diet
    - calorie goals
    - region
    - restrictions
    - meal type
    """

    # ---------------------------------------------------------
    # Input Data (External or Sensor Inputs)
    # ---------------------------------------------------------

    health_data: Dict
    """Raw health metrics collected from devices or APIs"""

    health_metric: Dict
    """Processed health metrics used by health agent"""

    journal_text: str
    """User-provided mental health journal text"""

    daily_journal: Dict
    """Structured daily journal entry saved in DB"""

    # ---------------------------------------------------------
    # Agent Outputs
    # ---------------------------------------------------------

    nutrition_plan: Dict
    """Meal plan generated by Nutrition Agent"""

    exercise_plan: Dict
    """Workout plan generated by Exercise Agent"""

    grocery_list: List[str]
    """List of grocery items derived from the meal plan"""

    mental_insights: Dict
    """Insights generated by Mental Health Agent"""

    # ---------------------------------------------------------
    # Approval Flags
    # ---------------------------------------------------------

    meal_plan_approved: bool
    """Indicates whether the meal plan was approved by user"""

    exercise_plan_approved: bool
    """Indicates whether the exercise plan was approved"""

    # ---------------------------------------------------------
    # Safety & Monitoring Flags
    # ---------------------------------------------------------

    anomaly_detected: bool
    """Indicates abnormal health metrics detected"""

    emergency_level: str
    """Emergency severity level (low / medium / high)"""

    compliance_passed: bool
    """Indicates if safety checks passed"""

    # ---------------------------------------------------------
    # Final API Response
    # ---------------------------------------------------------

    response: Dict
    """Final aggregated response returned to API client"""

    # ---------------------------------------------------------
    # Database Session
    # ---------------------------------------------------------

    db: Session
    """
    SQLAlchemy database session passed to agents
    for CRUD operations.
    """
# from typing import TypedDict, Optional, List, Dict
# from sqlalchemy.orm import Session 


# class OrchestratorState(TypedDict, total=False):

#     # Core user context
#     user_id: int
#     user_profile: Dict

#     # Inputs
#     health_data: Dict
#     health_metric: Dict
#     journal_text: str

#     daily_journal: Dict

#     # Agent outputs
#     nutrition_plan: Dict
#     exercise_plan: Dict
#     grocery_list: List[str]
#     mental_insights: Dict

#     # Approval flags
#     meal_plan_approved: bool
#     exercise_plan_approved: bool

#     # Safety flags
#     anomaly_detected: bool
#     emergency_level: str
#     compliance_passed: bool

#     # Final API response
#     response: Dict

#      # DB session
#     db: Session

