"""
Weekly Meal Plan CRUD Operations
--------------------------------

Handles all database operations related to weekly meal plans
generated by the Nutrition Agent.

These functions are designed to work seamlessly with:
- FastAPI services
- LangGraph agents
- Orchestrator state management

Author: Alma AI Backend
"""

from typing import Optional, List, Dict
from datetime import datetime, timedelta


from sqlalchemy.orm import Session
from sqlalchemy.exc import SQLAlchemyError

from app.models.weekly_meal_plan import WeeklyMealPlan
from app.core.logging_config import setup_logger
from app.core.exceptions import NutritionAgentError

# Initialize logger
logger = setup_logger(__name__)


# ---------------------------------------------------------
# CREATE OPERATIONS
# ---------------------------------------------------------

def create_weekly_meal_plan(
    db: Session,
    user_id: int,
    calories: Optional[int],
    diet: Optional[str],
    region: Optional[str],
    goal: Optional[str],
    restrictions: Optional[List[str]],
    meal_plan_text: str
) -> WeeklyMealPlan:
    """
    Create and store a new weekly meal plan generated by the Nutrition Agent.

    Args:
        db: Database session
        user_id: User identifier
        calories: Target calorie intake
        diet: Diet preference
        region: Cuisine region
        goal: Health goal
        restrictions: Dietary restrictions
        meal_plan_text: AI generated weekly meal plan

    Returns:
        WeeklyMealPlan object
    """

    try:
        logger.info(f"Creating weekly meal plan | user_id={user_id}")

        meal_plan = WeeklyMealPlan(
            user_id=user_id,
            calories=calories,
            diet=diet,
            region=region,
            goal=goal,
            restrictions=restrictions,
            meal_plan_text=meal_plan_text
        )

        db.add(meal_plan)
        db.commit()
        db.refresh(meal_plan)

        # Log creation
        meal_plan.log_creation()

        logger.info(f"Meal plan stored successfully | plan_id={meal_plan.id}")

        return meal_plan

    except SQLAlchemyError as e:
        db.rollback()
        logger.error(f"Database error while creating meal plan: {str(e)}")
        raise NutritionAgentError("Failed to create weekly meal plan")


# ---------------------------------------------------------
# READ OPERATIONS
# ---------------------------------------------------------

def get_meal_plan_by_id(
    db: Session,
    meal_plan_id: int
) -> Optional[WeeklyMealPlan]:
    """
    Fetch a meal plan by ID.

    Args:
        db: Database session
        meal_plan_id: Meal plan ID

    Returns:
        WeeklyMealPlan or None
    """

    try:
        logger.info(f"Fetching meal plan | plan_id={meal_plan_id}")

        meal_plan = (
            db.query(WeeklyMealPlan)
            .filter(WeeklyMealPlan.id == meal_plan_id)
            .first()
        )

        return meal_plan

    except SQLAlchemyError as e:
        logger.error(f"Error fetching meal plan: {str(e)}")
        raise NutritionAgentError("Failed to fetch meal plan")


def get_latest_user_meal_plan(
    db: Session,
    user_id: int
) -> Optional[WeeklyMealPlan]:
    """
    Fetch the latest meal plan generated for a user.

    This is typically used by the Nutrition Agent
    before generating a new plan.

    Args:
        db: Database session
        user_id: User ID

    Returns:
        Latest WeeklyMealPlan or None
    """

    try:
        logger.info(f"Fetching latest meal plan | user_id={user_id}")

        meal_plan = (
            db.query(WeeklyMealPlan)
            .filter(WeeklyMealPlan.user_id == user_id)
            .order_by(WeeklyMealPlan.created_at.desc())
            .first()
        )

        return meal_plan

    except SQLAlchemyError as e:
        logger.error(f"Error fetching latest meal plan: {str(e)}")
        raise NutritionAgentError("Failed to fetch latest meal plan")


def get_all_user_meal_plans(
    db: Session,
    user_id: int
) -> List[WeeklyMealPlan]:
    """
    Retrieve all meal plans generated for a user.

    Args:
        db: Database session
        user_id: User ID

    Returns:
        List of WeeklyMealPlan
    """

    try:
        logger.info(f"Fetching all meal plans | user_id={user_id}")

        plans = (
            db.query(WeeklyMealPlan)
            .filter(WeeklyMealPlan.user_id == user_id)
            .order_by(WeeklyMealPlan.created_at.desc())
            .all()
        )

        return plans

    except SQLAlchemyError as e:
        logger.error(f"Error fetching user meal plans: {str(e)}")
        raise NutritionAgentError("Failed to fetch user meal plans")



def get_current_week_meal_plan(
    db: Session,
    user_id: int
) -> Optional[WeeklyMealPlan]:
    """
    Fetch the meal plan created for the current week for a user.

    This function ensures that only one meal plan exists
    per user per week.

    Args:
        db: Database session
        user_id: User identifier

    Returns:
        WeeklyMealPlan if exists, otherwise None
    """

    try:
        logger.info(f"Fetching current week meal plan | user_id={user_id}")

        # ---------------------------------------------------------
        # Calculate start and end of current week (Monday → Sunday)
        # ---------------------------------------------------------

        today = datetime.utcnow()

        start_of_week = today - timedelta(days=today.weekday())
        start_of_week = start_of_week.replace(
            hour=0, minute=0, second=0, microsecond=0
        )

        end_of_week = start_of_week + timedelta(days=7)

        logger.debug(
            f"Week range | start={start_of_week} | end={end_of_week}"
        )

        # ---------------------------------------------------------
        # Query database
        # ---------------------------------------------------------

        meal_plan = (
            db.query(WeeklyMealPlan)
            .filter(
                WeeklyMealPlan.user_id == user_id,
                WeeklyMealPlan.created_at >= start_of_week,
                WeeklyMealPlan.created_at < end_of_week
            )
            .order_by(WeeklyMealPlan.created_at.desc())
            .first()
        )

        if meal_plan:
            logger.info(
                f"Current week meal plan found | plan_id={meal_plan.id}"
            )
        else:
            logger.info(
                f"No meal plan found for current week | user_id={user_id}"
            )

        return meal_plan

    except SQLAlchemyError as e:
        logger.error(f"Error fetching weekly meal plan: {str(e)}")
        raise NutritionAgentError("Failed to fetch current week meal plan")

# ---------------------------------------------------------
# UPDATE OPERATIONS
# ---------------------------------------------------------
from typing import Optional
from sqlalchemy.orm import Session
from sqlalchemy.exc import SQLAlchemyError
from datetime import datetime, timedelta

from app.models.weekly_meal_plan import WeeklyMealPlan
from app.core.logging_config import setup_logger
from app.core.exceptions import NutritionAgentError

logger = setup_logger(__name__)


def approve_meal_plan(
    db: Session,
    meal_plan_id: int,
    shop_number: Optional[str] = None
) -> Optional[WeeklyMealPlan]:
    """
    Approve a weekly meal plan and optionally set the grocery shop number.

    Args:
        db (Session): Database session.
        meal_plan_id (int): ID of the meal plan to approve.
        shop_number (str, optional): Grocery store number to associate.

    Returns:
        WeeklyMealPlan | None: Updated meal plan or None if not found.
    """
    try:
        logger.info("Approving meal plan | plan_id=%s", meal_plan_id)

        meal_plan = db.query(WeeklyMealPlan).filter(WeeklyMealPlan.id == meal_plan_id).first()
        if not meal_plan:
            logger.warning("Meal plan not found | plan_id=%s", meal_plan_id)
            return None

        # Update approval and shop number
        meal_plan.is_approved = True
        if shop_number:
            meal_plan.shop_number = shop_number

        db.commit()
        db.refresh(meal_plan)

        logger.info("Meal plan approved | plan_id=%s | shop_number=%s", meal_plan_id, shop_number)
        return meal_plan

    except SQLAlchemyError as e:
        db.rollback()
        logger.exception("Error approving meal plan | plan_id=%s", meal_plan_id)
        raise NutritionAgentError("Failed to approve meal plan") from e


def get_current_week_grocery_list(db: Session, user_id: int) -> Optional[dict]:
    """
    Fetch the grocery list for the current week's approved meal plan.

    Args:
        db (Session): Database session.
        user_id (int): User ID.

    Returns:
        dict | None: Grocery list dictionary if exists, otherwise None.
    """
    try:
        today = datetime.utcnow().date()
        week_start = today - timedelta(days=today.weekday())
        week_end = week_start + timedelta(days=7)

        meal_plan = (
            db.query(WeeklyMealPlan)
            .filter(
                WeeklyMealPlan.user_id == user_id,
                WeeklyMealPlan.is_approved == True,
                WeeklyMealPlan.created_at >= week_start,
                WeeklyMealPlan.created_at < week_end
            )
            .order_by(WeeklyMealPlan.created_at.desc())
            .first()
        )

        if not meal_plan:
            logger.info("No approved meal plan found for current week | user_id=%s", user_id)
            return None

        logger.info(
            "Fetched current week's grocery list | user_id=%s | plan_id=%s",
            user_id,
            meal_plan.id
        )

        return {
            "meal_plan_id": meal_plan.id,
            "shop_number": meal_plan.shop_number,
            "grocery_list": meal_plan.grocery_list
        }

    except SQLAlchemyError as e:
        logger.exception("Error fetching grocery list for user_id=%s", user_id)
        return None


def update_grocery_list(
    db: Session,
    meal_plan_id: int,
    grocery_list: Dict,
    shop_number: Optional[str] = None
) -> Optional[WeeklyMealPlan]:
    """
    Update grocery list generated by Grocery Agent.

    Args:
        db: Database session
        meal_plan_id: Meal plan ID
        grocery_list: Structured grocery list
        shop_number: Optional store reference

    Returns:
        Updated WeeklyMealPlan
    """

    try:
        logger.info(f"Updating grocery list | plan_id={meal_plan_id}")

        meal_plan = (
            db.query(WeeklyMealPlan)
            .filter(WeeklyMealPlan.id == meal_plan_id)
            .first()
        )

        if not meal_plan:
            logger.warning(f"Meal plan not found | id={meal_plan_id}")
            return None

        meal_plan.grocery_list = grocery_list
        meal_plan.shop_number = shop_number

        db.commit()
        db.refresh(meal_plan)

        logger.info(f"Grocery list updated | plan_id={meal_plan_id}")

        return meal_plan

    except SQLAlchemyError as e:
        db.rollback()
        logger.error(f"Error updating grocery list: {str(e)}")
        raise NutritionAgentError("Failed to update grocery list")


# ---------------------------------------------------------
# DELETE OPERATIONS
# ---------------------------------------------------------

def delete_meal_plan(
    db: Session,
    meal_plan_id: int
) -> bool:
    """
    Delete a meal plan.

    Args:
        db: Database session
        meal_plan_id: Meal plan ID

    Returns:
        True if deleted successfully
    """

    try:
        logger.info(f"Deleting meal plan | id={meal_plan_id}")

        meal_plan = (
            db.query(WeeklyMealPlan)
            .filter(WeeklyMealPlan.id == meal_plan_id)
            .first()
        )

        if not meal_plan:
            logger.warning(f"Meal plan not found | id={meal_plan_id}")
            return False

        db.delete(meal_plan)
        db.commit()

        logger.info(f"Meal plan deleted | id={meal_plan_id}")

        return True

    except SQLAlchemyError as e:
        db.rollback()
        logger.error(f"Error deleting meal plan: {str(e)}")
        raise NutritionAgentError("Failed to delete meal plan")
