import logging
from app.orchestrator.state import OrchestratorState
from app.services.send_whatsapp_message import send_whatsapp_message
from app.crud.user import get_phone_by_user_id


# Configure logger
logger = logging.getLogger("EmergencyAgent")
logger.setLevel(logging.INFO)


def emergency_alert_agent(state: OrchestratorState) -> OrchestratorState:
    """
    Emergency Alert Agent

    This agent checks the latest health data for a critical alert level.
    If a critical condition is detected, an emergency SMS notification
    is sent to the user's emergency contact.

    Workflow
    --------
    1. Retrieve health data from the orchestrator state.
    2. Check the alert level generated by the anomaly detection rules.
    3. If the alert level is "critical", send an emergency SMS.
    4. Update the orchestrator state with emergency_triggered flag.

    Args:
        state (OrchestratorState): Shared state passed between agents.

    Returns:
        OrchestratorState: Updated state with emergency status.
    """

    try:

        health_data = state.get("health_data")
        db = state.get("db")

        if not health_data:
            logger.info("No health data available in state.")
            # state["emergency_triggered"] = False
            return state

        alert_level = health_data.get("alert_level")

        if alert_level == "critical":
            state["emergency_triggered"] = True
            logger.warning("Critical alert detected. Triggering emergency SMS.")

            # Get emergency contact from user profile
            user_profile = state.get("user_profile", {})
            user_id = user_profile.get("user_id")

            phone_number = get_phone_by_user_id(db,user_id)

            if not phone_number:
                logger.error("Emergency contact not found in user profile.")
                state["emergency_triggered"] = True
                return state

            # Send emergency SMS
            send_whatsapp_message(
                to_number=phone_number,
                message=(
                    "🚨 CRITICAL HEALTH ALERT!\n"
                    f"Heart Rate: {health_data.get('heart_rate')}\n"
                    f"SpO2: {health_data.get('spo2')}\n"
                    f"BP: {health_data.get('bp_systolic')}/{health_data.get('bp_diastolic')}\n"
                    "Immediate attention required."
                )
            )

            state["emergency_triggered"] = True
            logger.info("Emergency SMS successfully triggered.")

        else:

            logger.info("Health status normal or warning. No emergency action.")
            state["emergency_triggered"] = False

    except Exception as e:

        logger.error(
            f"Error in emergency_alert_agent: {e}",
            exc_info=True
        )

        state["emergency_triggered"] = False

    return state