"""
Prompt templates for Nutrition Agent
"""

from typing import Dict


def build_nutrition_prompt(user_profile: Dict) -> str:
    return f"""
You are a professional dietitian and nutritionist.

Create a **7-day personalized meal plan** strictly for the user profile below.

------------------------
USER PROFILE
------------------------
Daily Calorie Target: {user_profile.get('calories')} kcal
Diet Type: {user_profile.get('diet')}
Goal: {user_profile.get('goal')}
Cuisine Region: {user_profile.get('region')}
Dietary Restrictions: {user_profile.get('restrictions')}
Meal Preference: {user_profile.get('meal_type')}

------------------------
MEAL PLAN REQUIREMENTS
------------------------
1. Total calories per day must be **close to the target ±50 kcal**.
2. Include **Breakfast, Lunch, Dinner, and 1–2 Healthy Snacks** per day.
3. Each meal MUST contain the following fields:

- Food name
- Quantity
- Ingredients
- Calories
- Preparation tip

4. Prefer balanced macronutrients: complex carbs, proteins, healthy fats, fiber.
5. Meals must be culturally relevant for the selected region.
6. Avoid processed foods unless necessary.
7. Ensure dietary restrictions are strictly followed.

------------------------
STRICT OUTPUT FORMAT
------------------------

Day 1

Breakfast:
Food name: <dish name>
Quantity: <grams, cups, or number of breads>
Ingredients: <ingredient list>
Calories: <number> kcal
Preparation tip: <short cooking instruction>

Lunch:
Food name: ...
Quantity: ...
Ingredients: ...
Calories: ...
Preparation tip: ...

Dinner:
Food name: ...
Quantity: ...
Ingredients: ...
Calories: ...
Preparation tip: ...

Snack:
Food name: ...
Quantity: ...
Ingredients: ...
Calories: ...
Preparation tip: ...

Daily Total Calories: XXX kcal


Repeat the same format for **Day 1 to Day 7**.

IMPORTANT:
- Always include **Food name:** exactly as written.
- Do not use bullet points.
- Do not add markdown symbols like * or **.
- Follow the format exactly.

------------------------
DISCLAIMER
------------------------
This meal plan is generated by an AI system and is intended for general informational purposes only. It is not a substitute for professional medical or nutritional advice. Consult a qualified healthcare professional before making significant dietary changes.
"""