"""
Prompt templates for Nutrition Agent
"""

from typing import Dict


def build_nutrition_prompt(user_profile: Dict) -> str:
    """
    Builds a structured, strict prompt for generating a weekly meal plan.

    The prompt enforces:
    - daily calorie target (ingredient-based)
    - food quantities (grams, pieces, breads)
    - preparation tips
    - culturally relevant healthy meals
    - structured readable format

    Args:
        user_profile (Dict): User profile containing dietary preferences and goals.

    Returns:
        str: Formatted LLM prompt string
    """

    return f"""
You are a professional dietitian and nutritionist. 

Create a **7-day personalized meal plan** strictly for the user profile below.

------------------------
USER PROFILE
------------------------
Daily Calorie Target: {user_profile.get('calories')} kcal
Diet Type: {user_profile.get('diet')}
Goal: {user_profile.get('goal')}
Cuisine Region: {user_profile.get('region')}
Dietary Restrictions: {user_profile.get('restrictions')}
Meal Preference: {user_profile.get('meal_type')}

------------------------
MEAL PLAN REQUIREMENTS
------------------------
1. Total calories per day must be **close to the target ±50 kcal**.
2. Include **Breakfast, Lunch, Dinner, and 1–2 Healthy Snacks** per day.
3. For each meal include:
   - Food name
   - **Quantity in grams, cups, or number of breads**
   - Ingredients used
   - Calories per meal (ingredient-based calculation)
   - Preparation tips (simple and actionable)
4. Prefer **balanced macronutrients**: complex carbs, proteins, healthy fats, fiber.
5. Meals must be **culturally relevant** for the selected region.
6. Avoid processed foods unless necessary.
7. Ensure **dietary restrictions** are strictly followed.

------------------------
OUTPUT FORMAT
------------------------
Day 1
Breakfast:
Food name (quantity + ingredients)
Calories: XXX kcal
Preparation tip: ...

Lunch:
...

Dinner:
...

Snacks:
...

Daily Total Calories: XXX kcal

Repeat this for all 7 days.

------------------------
DISCLAIMER
------------------------
"This meal plan is generated by an AI system and is intended for general informational purposes only. It is not a substitute for professional medical or nutritional advice. Consult a qualified healthcare professional before making significant dietary changes."
"""
