name: CI/CD Pipeline

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
# =========================
# TEST JOB
# =========================
  test:
    name: Run Tests
    runs-on: ubuntu-latest


   

     

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r backend/requirements.txt


      - run: pytest -v

# =========================
# BUILD BACKEND
# =========================
  build-backend:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/curamyn-backend:latest

# =========================
# DEPLOY TO EC2
# =========================
  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend]

    if: github.ref == 'refs/heads/main'

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/alma_backend:latest

            docker compose pull
            docker compose down
            docker compose up -d

            echo "Deployed successfully"

